################################  \u670D\u52A1\u5668\u914D\u7F6E  ################################
server:
  servlet:
    context-path: /dreamcc
  port: 8088
################################ \u6570\u636E\u6E90\u914D\u7F6E  ################################
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource